# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_message/angles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class angles(genpy.Message):
  _md5sum = "354d100d75e8581dc7dd85b447e1a363"
  _type = "custom_message/angles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float64 theta1
std_msgs/Float64 theta2
std_msgs/Float64 theta3

================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['theta1','theta2','theta3']
  _slot_types = ['std_msgs/Float64','std_msgs/Float64','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       theta1,theta2,theta3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(angles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.theta1 is None:
        self.theta1 = std_msgs.msg.Float64()
      if self.theta2 is None:
        self.theta2 = std_msgs.msg.Float64()
      if self.theta3 is None:
        self.theta3 = std_msgs.msg.Float64()
    else:
      self.theta1 = std_msgs.msg.Float64()
      self.theta2 = std_msgs.msg.Float64()
      self.theta3 = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.theta1.data, _x.theta2.data, _x.theta3.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.theta1 is None:
        self.theta1 = std_msgs.msg.Float64()
      if self.theta2 is None:
        self.theta2 = std_msgs.msg.Float64()
      if self.theta3 is None:
        self.theta3 = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.theta1.data, _x.theta2.data, _x.theta3.data,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.theta1.data, _x.theta2.data, _x.theta3.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.theta1 is None:
        self.theta1 = std_msgs.msg.Float64()
      if self.theta2 is None:
        self.theta2 = std_msgs.msg.Float64()
      if self.theta3 is None:
        self.theta3 = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.theta1.data, _x.theta2.data, _x.theta3.data,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
